#!/bin/bash
# Does MAIN -- the design going to layout -- survive PRBS7 at ff/125C/1.32V?
# The branch dies there (e2e_prbs_ff125.log: clock 49 nV).  If main dies too,
# the pump-bias problem is inherited from the original, not introduced by the
# branch.  Uses main's own netlist and deck by absolute path; writes nothing
# into the main repository.
set -u
M=/home/ttuser/ssh_analog/ihp-analog-equalizer
W=/home/ttuser/ssh_analog/ct-worktree
PDK=/home/ttuser/pdk/ihp-sg13cmos5l/libs.tech/ngspice
mkdir -p $W/sim/scratch && cd $W/sim/scratch

cat > main_seed_ff125.spice <<DECK
* main's ring (0.9 um / 7355 ohm, no trim legs) at ff/125C/1.32V: lock point.
.control
pre_osdi $PDK/osdi/psp103.osdi
pre_osdi $PDK/osdi/psp103_nqs.osdi
pre_osdi $PDK/osdi/r3_cmc.osdi
pre_osdi $PDK/osdi/cap_cmomf.osdi
.endc
.lib $PDK/models/cornerMOSlv.lib mos_ff
.lib $PDK/models/cornerRES.lib  res_typ
.lib $PDK/models/cornerCAP.lib  cap_typ
.include $M/sim/netlists/blocks.inc
.include $W/sim/decks/ring_p.inc
.global sub!
Vsub sub! 0 0
VDD VDD 0 1.32
VSS VSS 0 0
Vc vctrl 0 0.5
x1 VDD VSS vctrl vop vom ring_p
.ic v(vop)=1.0 v(vom)=0.4
.options method=gear reltol=1e-4 abstol=1e-12 vntol=1e-6
.control
save v(vop) v(vom) v(x1.net1)
alterparam Lin = 0.9
alterparam Rload = 7355
reset
set temp = 125
foreach vc 0.300 0.325 0.350 0.375 0.400 0.425 0.450 0.475 0.500 0.550 0.600 0.650
 alter Vc dc = \$vc
 tran 5p 120n
 let p_vctrl = \$vc
 meas tran t1 when v(vop)=v(vom) rise=6
 meas tran t2 when v(vop)=v(vom) rise=26
 let fosc = 20 / (t2 - t1)
 meas tran vmax max v(x1.net1) from=60n to=120n
 meas tran vmin min v(x1.net1) from=60n to=120n
 let swing = vmax - vmin
 print p_vctrl fosc swing
 echo "ROWEND"
end
quit
.endc
.end
DECK
../../tools/safe_ngspice.sh main_seed_ff125.spice main_seed_ff125.log 2500 2400 2000 >/dev/null 2>&1

SEED=$(python3 - <<'PY'
import re
num=re.compile(r"^(p_vctrl|fosc|swing) = (-?\d\.\d+e[-+]\d{2})\s*$")
pts=[]; pend={}
for line in open('main_seed_ff125.log'):
    if line.startswith("ROWEND"): pend={}; continue
    m=num.match(line)
    if m:
        pend[m.group(1)]=float(m.group(2))
        if len(pend)==3: pts.append((pend['p_vctrl'],pend['fosc']/1e6,pend['swing'])); pend={}
g=sorted((v,f) for v,f,s in pts if s>=0.15)
for (v1,f1),(v2,f2) in zip(g,g[1:]):
    if min(f1,f2)<=600.6<=max(f1,f2):
        print(f"{v1+(600.6-f1)*(v2-v1)/(f2-f1):.3f}"); break
PY
)
echo "### main ring seed at ff/125C/1.32V: ${SEED:-NOT FOUND}"
python3 - <<'PY'
import re
num=re.compile(r"^(p_vctrl|fosc|swing) = (-?\d\.\d+e[-+]\d{2})\s*$")
pend={}
for line in open('main_seed_ff125.log'):
    if line.startswith("ROWEND"): pend={}; continue
    m=num.match(line)
    if m:
        pend[m.group(1)]=float(m.group(2))
        if len(pend)==3: print(f"   vctrl {pend['p_vctrl']:.3f}  {pend['fosc']/1e6:7.1f} MHz  swing {pend['swing']:.3f}"); pend={}
PY
if [ -z "$SEED" ]; then echo "600.6 MHz not reachable by main's ring at this corner -- that is itself the answer"; echo "=== MAIN FF125 DONE ==="; exit 0; fi

python3 - "$SEED" "$M" <<'PY'
import sys, re
seed, M = sys.argv[1], sys.argv[2]
s=open(f"{M}/sim/decks/e2e_prbs.spice").read()
def sub(pat, rep, count_expected=1, flags=re.M):
    global s
    s2, n = re.subn(pat, rep, s, flags=flags)
    assert n==count_expected, f"{pat!r}: {n} matches"
    s = s2
sub(r"cornerMOSlv\.lib mos_tt", "cornerMOSlv.lib mos_ff")
sub(r"^VDD Vdd 0 1\.2\s*$", "VDD Vdd 0 1.32")
sub(r"^\.ic v\(x1\.x2\.net1\)=.*$", f".ic v(x1.x2.net1)={seed}")
sub(r"^\.include \.\./netlists/blocks\.inc\s*$", f".include {M}/sim/netlists/blocks.inc\n.temp 125")
sub(r"^\.include prbs7_3u\.inc\s*$", f".include {M}/sim/decks/prbs7_3u.inc")
assert "vcoarse" not in s, "main's deck should know nothing of vcoarse"
open("main_prbs_ff125.spice","w").write("* main's e2e_prbs.spice moved to ff/125C/1.32V and reseeded; generated by main_prbs_ff125.sh\n"+s)
PY
../../tools/safe_ngspice.sh main_prbs_ff125.spice main_prbs_ff125.log 2500 5400 2000 >/dev/null 2>&1
echo "### main, PRBS7, ff/125C/1.32V:"
grep -E "^(f_long|f_err|vctrl_s1|vctrl_s2|vctrl_s3|vctrl_min|vctrl_max|vctrl_ripp|rclk_swing|ctle_swing) = " main_prbs_ff125.log
grep -m2 -iE "failed" main_prbs_ff125.log || true
echo "=== MAIN FF125 DONE ==="
