#!/usr/bin/env python3
"""Pull one `.subckt` out of sim/netlists/blocks.inc, with its children.

    tools/cell_netlist.py robs_xor > mag/robs_xor.spice
    tools/cell_netlist.py --flat CTLE        # devices only, no subcell defs
    tools/cell_netlist.py --list             # every cell, leaves first

Magic's `magic::netlist_to_layout` and netgen both want a netlist containing
the cell under test.  blocks.inc contains the whole chip, and feeding that to
either of them does far more than you asked for -- see trap 2.4.

Children are included by default and in dependency order, because a cell whose
subcells are missing gives netgen a "cell not found" rather than a mismatch,
which reads like a broken script instead of a missing layout.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BLOCKS = ROOT / "sim" / "netlists" / "blocks.inc"
DEV = ("sg13_", "rhigh", "rppd", "rsil", "cap_")


def parse(text):
    cells, cur, buf = {}, None, []
    for line in text.splitlines():
        if line.startswith(".subckt "):
            cur, buf = line.split()[1], [line]
        elif cur and line.startswith(".ends"):
            buf.append(".ends")
            cells[cur] = buf
            cur = None
        elif cur:
            buf.append(line)
    return cells


def children(cells, name):
    """Subcell names this cell instantiates, deepest first, no duplicates."""
    out = []
    for line in cells.get(name, []):
        if line[:1] not in "Xx":
            continue
        t = line.split()
        if any(x.startswith(DEV) for x in t):
            continue                      # a device, not a subcell
        kid = t[-1]
        if kid in cells:
            for g in children(cells, kid):
                if g not in out:
                    out.append(g)
            if kid not in out:
                out.append(kid)
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("cell", nargs="?")
    ap.add_argument("--flat", action="store_true",
                    help="omit subcell definitions (devices only)")
    ap.add_argument("--list", action="store_true")
    a = ap.parse_args()

    if not BLOCKS.exists():
        sys.exit(f"{BLOCKS} is missing -- run tools/netlist.sh")
    cells = parse(BLOCKS.read_text())

    if a.list:
        for n in sorted(cells, key=lambda c: (len(children(cells, c)), c)):
            kids = children(cells, n)
            ndev = sum(1 for l in cells[n]
                       if l[:1] in "Xx" and any(x.startswith(DEV) for x in l.split()))
            print(f"{n:<28}{ndev:>3} devices   "
                  f"{'leaf' if not kids else 'needs: ' + ' '.join(kids)}")
        return 0
    if not a.cell:
        ap.error("give a cell name, or --list")
    if a.cell not in cells:
        sys.exit(f"no cell {a.cell!r} in blocks.inc (try --list)")

    print(f"* {a.cell} and its children, from sim/netlists/blocks.inc")
    print("* generated by tools/cell_netlist.py -- do not edit")
    for n in ([] if a.flat else children(cells, a.cell)) + [a.cell]:
        print("\n".join(cells[n]))
        print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
