v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
T {cp_bias -- GENERATED by tools/gen_coarse_loop.py from
sim/decks/cp_bias.inc.  Do not edit: edit the include and
re-run.  Connectivity is by label, one lab_wire on every pin.
4 devices.  Charge-pump bias from ibias; see docs/HANDBOOK.md.} -260 -200 0 0 0.3 0.3 {}
C {sg13cmos5l_pr/sg13_lv_nmos.sym} 0 0 0 0 {name=MN1
l=8.000000e-06
w=2.500000e-07
ng=1
m=1
model=sg13_lv_nmos
mm_ok=1
spiceprefix=X}
C {devices/lab_wire.sym} 20 -30 0 0 {name=MN1_D sig_type=std_logic lab=bias_p}
C {devices/lab_wire.sym} -20 0 0 0 {name=MN1_G sig_type=std_logic lab=vbias}
C {devices/lab_wire.sym} 20 30 0 0 {name=MN1_S sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 20 0 0 0 {name=MN1_B sig_type=std_logic lab=VSS}
C {sg13cmos5l_pr/sg13_lv_pmos.sym} 140 0 0 0 {name=MPD
l=1.000000e-06
w=2.000000e-06
ng=1
m=1
model=sg13_lv_pmos
mm_ok=1
spiceprefix=X}
C {devices/lab_wire.sym} 160 30 0 0 {name=MPD_D sig_type=std_logic lab=bias_p}
C {devices/lab_wire.sym} 120 0 0 0 {name=MPD_G sig_type=std_logic lab=bias_p}
C {devices/lab_wire.sym} 160 -30 0 0 {name=MPD_S sig_type=std_logic lab=VDD}
C {devices/lab_wire.sym} 160 0 0 0 {name=MPD_B sig_type=std_logic lab=VDD}
C {sg13cmos5l_pr/sg13_lv_pmos.sym} 280 0 0 0 {name=MP2
l=1.000000e-06
w=1.450000e-06
ng=1
m=1
model=sg13_lv_pmos
mm_ok=1
spiceprefix=X}
C {devices/lab_wire.sym} 300 30 0 0 {name=MP2_D sig_type=std_logic lab=bias_n}
C {devices/lab_wire.sym} 260 0 0 0 {name=MP2_G sig_type=std_logic lab=bias_p}
C {devices/lab_wire.sym} 300 -30 0 0 {name=MP2_S sig_type=std_logic lab=VDD}
C {devices/lab_wire.sym} 300 0 0 0 {name=MP2_B sig_type=std_logic lab=VDD}
C {sg13cmos5l_pr/sg13_lv_nmos.sym} 420 0 0 0 {name=MND
l=1.000000e-06
w=1.000000e-06
ng=1
m=1
model=sg13_lv_nmos
mm_ok=1
spiceprefix=X}
C {devices/lab_wire.sym} 440 -30 0 0 {name=MND_D sig_type=std_logic lab=bias_n}
C {devices/lab_wire.sym} 400 0 0 0 {name=MND_G sig_type=std_logic lab=bias_n}
C {devices/lab_wire.sym} 440 30 0 0 {name=MND_S sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 440 0 0 0 {name=MND_B sig_type=std_logic lab=VSS}
C {devices/iopin.sym} 0 220 0 0 {name=P0 lab=VDD}
C {devices/iopin.sym} 140 220 0 0 {name=P1 lab=VSS}
C {devices/ipin.sym} 280 220 0 0 {name=P2 lab=vbias}
C {devices/opin.sym} 420 220 0 0 {name=P3 lab=bias_n}
C {devices/opin.sym} 560 220 0 0 {name=P4 lab=bias_p}
