v {xschem version=3.4.5 file_version=1.2
}
G {}
K {}
V {}
S {}
E {}
T {sb_inverter -- GENERATED by tools/gen_coarse_loop.py from
sim/decks/sb_inverter.inc.  Do not edit: edit the include and
re-run.  Connectivity is by label, one lab_wire on every pin.
4 devices.  Self-biased clock stage; see docs/HANDBOOK.md.} -260 -200 0 0 0.3 0.3 {}
C {sg13cmos5l_pr/cap_cmomf.sym} 0 0 0 0 {name=CC
l=8.800000e-06
w=8.800000e-06
m=1
mmin=1
mmax=4
subblock=0
model=cap_cmomf
mm_ok=1
spiceprefix=X}
C {devices/lab_wire.sym} 0 -30 0 0 {name=CC_c0 sig_type=std_logic lab=in}
C {devices/lab_wire.sym} 0 30 0 0 {name=CC_c1 sig_type=std_logic lab=sbin}
C {sg13cmos5l_pr/rhigh.sym} 140 0 0 0 {name=RFB
l=7.000000e-05
w=1.000000e-06
m=1
b=0
body=sub!
model=rhigh
mm_ok=1
spiceprefix=X}
C {devices/lab_wire.sym} 140 -30 0 0 {name=RFB_P sig_type=std_logic lab=sbin}
C {devices/lab_wire.sym} 140 30 0 0 {name=RFB_M sig_type=std_logic lab=out}
C {sg13cmos5l_pr/sg13_lv_pmos.sym} 280 0 0 0 {name=MP
l=1.300000e-07
w=2.000000e-06
ng=1
m=1
model=sg13_lv_pmos
mm_ok=1
spiceprefix=X}
C {devices/lab_wire.sym} 300 30 0 0 {name=MP_D sig_type=std_logic lab=out}
C {devices/lab_wire.sym} 260 0 0 0 {name=MP_G sig_type=std_logic lab=sbin}
C {devices/lab_wire.sym} 300 -30 0 0 {name=MP_S sig_type=std_logic lab=VDD}
C {devices/lab_wire.sym} 300 0 0 0 {name=MP_B sig_type=std_logic lab=VDD}
C {sg13cmos5l_pr/sg13_lv_nmos.sym} 420 0 0 0 {name=MN
l=1.300000e-07
w=1.000000e-06
ng=1
m=1
model=sg13_lv_nmos
mm_ok=1
spiceprefix=X}
C {devices/lab_wire.sym} 440 -30 0 0 {name=MN_D sig_type=std_logic lab=out}
C {devices/lab_wire.sym} 400 0 0 0 {name=MN_G sig_type=std_logic lab=sbin}
C {devices/lab_wire.sym} 440 30 0 0 {name=MN_S sig_type=std_logic lab=VSS}
C {devices/lab_wire.sym} 440 0 0 0 {name=MN_B sig_type=std_logic lab=VSS}
C {devices/iopin.sym} 0 220 0 0 {name=P0 lab=VDD}
C {devices/iopin.sym} 140 220 0 0 {name=P1 lab=VSS}
C {devices/ipin.sym} 280 220 0 0 {name=P2 lab=in}
C {devices/opin.sym} 420 220 0 0 {name=P3 lab=out}
